ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\user\AppData\Roaming
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_14112_CWEDDGZBHTVAWQAY
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-KHPJM2I
COMSPEC=C:\Windows\system32\cmd.exe
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\user
IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAInSSmwt9D0GmIaBmPlYNcAQAAAACAAAAAAAQZgAAAAEAACAAAAAPg6GBte1GEJHxwP7vsQzSxKTuLMy2Q7fXPVaYKvpEpwAAAAAOgAAAAAIAACAAAAB8QQlEcoEILcgvoMcBK2BBXMeFO0Czrx///TOnMqONkmAAAADG6Zdvj5l0nqOrLvePPffz4v/bufq/52sgcAJmrf+uWrVuKyS4cB0eRYz1kKbjwTPNIXZvJ/w0QiML1aJbLbXu7ajurIj0fmANYPAIFJnvMs8qwPCdRcw/rtZI3eKHsTZAAAAAZn3x979gcACKlGcUi2r6+FDGdCqpQZ9ytJPozxNyxAlhgrQLF5XP8xoDQvBGe0YYZDDwB+OQW25/HWeNkn8Jjw==
LOCALAPPDATA=C:\Users\user\AppData\Local
LOGONSERVER=\\DESKTOP-KHPJM2I
NUMBER_OF_PROCESSORS=16
ONEDRIVE=C:\Users\user\OneDrive
ONEDRIVECONSUMER=C:\Users\user\OneDrive
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
PATH=c:\Users\user\.vscode\extensions\ms-python.python-2024.8.1\python_files\deactivate\powershell;C:\Users\user\OneDrive\Desktop\Shiny Projects\venv\Scripts;c:\Users\user\.vscode\extensions\ms-python.python-2024.8.1\python_files\deactivate\powershell;C:\Users\user\OneDrive\Desktop\Shiny Projects\venv\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Users\user\anaconda3;C:\Users\user\anaconda3\Library\mingw-w64\bin;C:\Users\user\anaconda3\Library\usr\bin;C:\Users\user\anaconda3\Library\bin;C:\Users\user\anaconda3\Scripts;C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python312\;C:\Users\user\AppData\Local\Programs\Python\Launcher\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\user\AppData\Local\GitHubDesktop\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9a03
PROGRAMDATA=C:\ProgramData
PROGRAMFILES=C:\Program Files
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Users\user\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\Users\user\AppData\Local\Temp
TMP=C:\Users\user\AppData\Local\Temp
USERDOMAIN=DESKTOP-KHPJM2I
USERDOMAIN_ROAMINGPROFILE=DESKTOP-KHPJM2I
USERNAME=user
USERPROFILE=C:\Users\user
WINDIR=C:\Windows
WSLENV=WT_SESSION:WT_PROFILE_ID:
WT_PROFILE_ID={61c54bbd-c2c6-5271-96e7-009a87ff44bf}
WT_SESSION=1c38bc94-8daa-4af2-8ac8-b8f6cbd6c8cd
ZES_ENABLE_SYSMAN=1
PYTHONSTARTUP=c:\Users\user\.vscode\extensions\ms-python.python-2024.8.1\python_files\pythonrc.py
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.90.2
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-33b19ccea0-sock
VIRTUAL_ENV=C:\Users\user\OneDrive\Desktop\Shiny Projects\venv
VIRTUAL_ENV_PROMPT=venv
VSCODE_INJECTION=1
